export const indianBanks = [
  { value: "state_bank_of_india", label: "State Bank of India" },
  { value: "punjab_national_bank", label: "Punjab National Bank" },
  { value: "bank_of_baroda", label: "Bank of Baroda" },
  { value: "canara_bank", label: "Canara Bank" },
  { value: "union_bank_of_india", label: "Union Bank of India" },
  { value: "hdfc_bank", label: "HDFC Bank" },
  { value: "icici_bank", label: "ICICI Bank" },
  { value: "axis_bank", label: "Axis Bank" },
  { value: "kotak_mahindra_bank", label: "Kotak Mahindra Bank" },
  { value: "indusind_bank", label: "IndusInd Bank" },
  { value: "yes_bank", label: "Yes Bank" },
  { value: "idbi_bank", label: "IDBI Bank" },
  { value: "bank_of_india", label: "Bank of India" },
  { value: "central_bank_of_india", label: "Central Bank of India" },
  { value: "indian_bank", label: "Indian Bank" },
  { value: "uco_bank", label: "UCO Bank" },
  { value: "bank_of_maharashtra", label: "Bank of Maharashtra" },
  { value: "indian_overseas_bank", label: "Indian Overseas Bank" },
  { value: "punjab_and_sind_bank", label: "Punjab & Sind Bank" },
  { value: "federal_bank", label: "Federal Bank" },
  { value: "south_indian_bank", label: "South Indian Bank" },
  { value: "karur_vysya_bank", label: "Karur Vysya Bank" },
  { value: "karnataka_bank", label: "Karnataka Bank" },
  { value: "jammu_and_kashmir_bank", label: "Jammu & Kashmir Bank" },
  { value: "city_union_bank", label: "City Union Bank" },
  { value: "bandhan_bank", label: "Bandhan Bank" },
  { value: "csb_bank", label: "CSB Bank" },
  { value: "dcb_bank", label: "DCB Bank" },
  { value: "dhanlaxmi_bank", label: "Dhanlaxmi Bank" },
  { value: "idfc_first_bank", label: "IDFC First Bank" },
  { value: "rbl_bank", label: "RBL Bank" },
];