export interface Product {
  id: string
  name: string
  description: string
  price: number
  discount: number
  category: string
  subcategory: string
  image: string
  rating: number
  reviewCount: number
  inStock: boolean
  isNew: boolean
  isFeatured: boolean
}

export interface Category {
  label: string
  value: string
  count: number
  subcategories: Subcategory[]
}

export interface Subcategory {
  label: string
  value: string
  count: number
}

// Product categories with subcategories based on the provided images
export const productCategories: Category[] = [
  {
    label: "Agro Products",
    value: "agro-products",
    count: 28,
    subcategories: [
      { label: "Seeds", value: "seeds", count: 4 },
      { label: "Fertilizers & Manures", value: "fertilizers-manures", count: 4 },
      { label: "Farming Tools", value: "farming-tools", count: 3 },
      { label: "Organic Pesticides", value: "organic-pesticides", count: 3 },
      { label: "Gardening Essentials", value: "gardening-essentials", count: 4 },
      { label: "Agro Processed Products", value: "agro-processed-products", count: 2 },
    ],
  },
  {
    label: "Eco Products",
    value: "eco-products",
    count: 19,
    subcategories: [
      { label: "Home Products", value: "home-products", count: 6 },
      { label: "Kitchen Products", value: "kitchen-products", count: 3 },
      { label: "Eco-Friendly Stationery", value: "eco-friendly-stationery", count: 3 },
      { label: "Cleaning Essentials", value: "cleaning-essentials", count: 3 },
    ],
  },
  {
    label: "Herbal Products",
    value: "herbal-products",
    count: 18,
    subcategories: [
      { label: "Raw Herbs", value: "raw-herbs", count: 6 },
      { label: "Herbal Powders", value: "herbal-powders", count: 5 },
      { label: "Herbal Juices & Extracts", value: "herbal-juices-extracts", count: 4 },
      { label: "Health Mixes", value: "health-mixes", count: 3 },
    ],
  },
  {
    label: "Natural Cosmetics",
    value: "natural-cosmetics",
    count: 18,
    subcategories: [
      { label: "Hair Care", value: "hair-care", count: 5 },
      { label: "Skin Care", value: "skin-care", count: 5 },
      { label: "Bath & Body", value: "bath-body", count: 3 },
      { label: "Oral Care", value: "oral-care", count: 3 },
    ],
  },
]

// Mock products data based on the provided images
const mockProducts: Product[] = [
  // AGRO PRODUCTS - Seeds
  {
    id: "agro-seed-1",
    name: "Paddy Seeds (Rice varieties)",
    description: "High-quality paddy seeds for traditional rice cultivation.",
    price: 120,
    discount: 0,
    category: "Agro Products",
    subcategory: "Seeds",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviewCount: 28,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "agro-seed-2",
    name: "Vegetable Seeds (Tomato, Brinjal, Chilli, etc.)",
    description: "Organic vegetable seed mix for home gardening.",
    price: 85,
    discount: 10,
    category: "Agro Products",
    subcategory: "Seeds",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.2,
    reviewCount: 15,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },
  {
    id: "agro-seed-3",
    name: "Fruit Seeds (Papaya, Guava, Banana, etc.)",
    description: "Collection of fruit seeds for growing your own fruit trees.",
    price: 150,
    discount: 0,
    category: "Agro Products",
    subcategory: "Seeds",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.3,
    reviewCount: 22,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "agro-seed-4",
    name: "Herbal Seeds (Tulsi, Vetiver, Aloe Vera)",
    description: "Medicinal and aromatic herb seeds for your garden.",
    price: 110,
    discount: 0,
    category: "Agro Products",
    subcategory: "Seeds",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviewCount: 42,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },

  // AGRO PRODUCTS - Fertilizers & Manures
  {
    id: "agro-fert-1",
    name: "Vermicompost - 5kg",
    description: "100% organic vermicompost for all plants and vegetables.",
    price: 450,
    discount: 5,
    category: "Agro Products",
    subcategory: "Fertilizers & Manures",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviewCount: 56,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "agro-fert-2",
    name: "Cow Dung Manure - 2kg",
    description: "Traditional organic fertilizer for healthy plant growth.",
    price: 180,
    discount: 0,
    category: "Agro Products",
    subcategory: "Fertilizers & Manures",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.3,
    reviewCount: 31,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "agro-fert-3",
    name: "Panchagavya - 1L",
    description: "Traditional bio-fertilizer made from five cow products.",
    price: 220,
    discount: 0,
    category: "Agro Products",
    subcategory: "Fertilizers & Manures",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 24,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },
  {
    id: "agro-fert-4",
    name: "Bio-Fertilizers (Azospirillum, Phosphobacteria) - 500g",
    description: "Microbial bio-fertilizers to enhance soil fertility naturally.",
    price: 195,
    discount: 0,
    category: "Agro Products",
    subcategory: "Fertilizers & Manures",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.4,
    reviewCount: 19,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },

  // AGRO PRODUCTS - Farming Tools
  {
    id: "agro-tool-1",
    name: "Hand Tools Set (Weeders, Pruners, Shears)",
    description: "Essential hand tools for gardening and farming.",
    price: 1200,
    discount: 15,
    category: "Agro Products",
    subcategory: "Farming Tools",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.4,
    reviewCount: 38,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "agro-tool-2",
    name: "Organic Pest Control Sprayers",
    description: "Manual sprayers for applying organic pesticides and fertilizers.",
    price: 850,
    discount: 0,
    category: "Agro Products",
    subcategory: "Farming Tools",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.2,
    reviewCount: 19,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "agro-tool-3",
    name: "Drip Irrigation Kits",
    description: "Water-saving drip irrigation system for efficient gardening.",
    price: 1500,
    discount: 10,
    category: "Agro Products",
    subcategory: "Farming Tools",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 27,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },

  // AGRO PRODUCTS - Organic Pesticides
  {
    id: "agro-pest-1",
    name: "Neem Oil - 500ml",
    description: "Natural pesticide and fungicide for organic gardening.",
    price: 350,
    discount: 0,
    category: "Agro Products",
    subcategory: "Organic Pesticides",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviewCount: 45,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "agro-pest-2",
    name: "Pungam Oil - 500ml",
    description: "Traditional organic pesticide for crop protection.",
    price: 320,
    discount: 5,
    category: "Agro Products",
    subcategory: "Organic Pesticides",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.3,
    reviewCount: 22,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "agro-pest-3",
    name: "Herbal Pest Repellents - 250g",
    description: "Blend of herbs to naturally repel garden pests.",
    price: 280,
    discount: 0,
    category: "Agro Products",
    subcategory: "Organic Pesticides",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviewCount: 33,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },

  // AGRO PRODUCTS - Gardening Essentials
  {
    id: "agro-garden-1",
    name: "Grow Bags (Cocopeat Grow Bags) - Set of 5",
    description: "Eco-friendly grow bags made from coconut coir for container gardening.",
    price: 550,
    discount: 0,
    category: "Agro Products",
    subcategory: "Gardening Essentials",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 37,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "agro-garden-2",
    name: "Potting Mix - 5kg",
    description: "Balanced potting soil mix for healthy plant growth.",
    price: 420,
    discount: 5,
    category: "Agro Products",
    subcategory: "Gardening Essentials",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.4,
    reviewCount: 29,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "agro-garden-3",
    name: "Garden Compost - 5kg",
    description: "Nutrient-rich compost for garden soil enrichment.",
    price: 380,
    discount: 0,
    category: "Agro Products",
    subcategory: "Gardening Essentials",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviewCount: 31,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "agro-garden-4",
    name: "Cocopeat Blocks - Pack of 3",
    description: "Compressed cocopeat blocks that expand with water for soil-less gardening.",
    price: 300,
    discount: 0,
    category: "Agro Products",
    subcategory: "Gardening Essentials",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviewCount: 42,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },

  // AGRO PRODUCTS - Agro Processed Products
  {
    id: "agro-processed-1",
    name: "Millet Varieties (Foxtail, Pearl Millet, Kodo Millet) - 1kg",
    description: "Assorted traditional millets for healthy cooking.",
    price: 250,
    discount: 0,
    category: "Agro Products",
    subcategory: "Agro Processed Products",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviewCount: 53,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "agro-processed-2",
    name: "Traditional Rice Varieties (Seeraga Samba, Black Rice, Red Rice) - 1kg",
    description: "Heritage rice varieties with unique flavors and health benefits.",
    price: 320,
    discount: 0,
    category: "Agro Products",
    subcategory: "Agro Processed Products",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.9,
    reviewCount: 64,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },

  // ECO PRODUCTS - Home Products
  {
    id: "eco-home-1",
    name: "Areca Leaf Plates - Pack of 10",
    description: "100% biodegradable disposable plates made from fallen areca palm leaves.",
    price: 180,
    discount: 0,
    category: "Eco Products",
    subcategory: "Home Products",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 72,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "eco-home-2",
    name: "Bamboo Toothbrushes - Pack of 4",
    description: "Biodegradable toothbrushes with bamboo handles and BPA-free bristles.",
    price: 250,
    discount: 10,
    category: "Eco Products",
    subcategory: "Home Products",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviewCount: 58,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "eco-home-3",
    name: "Wooden Cutlery Set",
    description: "Reusable wooden cutlery set including fork, spoon, and knife.",
    price: 350,
    discount: 0,
    category: "Eco Products",
    subcategory: "Home Products",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.3,
    reviewCount: 41,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "eco-home-4",
    name: "Coconut Shell Products (Bowls, Cups) - Set of 2",
    description: "Handcrafted bowls and cups made from coconut shells.",
    price: 450,
    discount: 0,
    category: "Eco Products",
    subcategory: "Home Products",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviewCount: 36,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },
  {
    id: "eco-home-5",
    name: "Palm Leaf Baskets - Set of 3",
    description: "Traditional handwoven baskets made from palm leaves.",
    price: 550,
    discount: 5,
    category: "Eco Products",
    subcategory: "Home Products",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.4,
    reviewCount: 29,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "eco-home-6",
    name: "Banana Fiber Products - Assorted",
    description: "Eco-friendly home decor items made from banana fiber.",
    price: 650,
    discount: 0,
    category: "Eco Products",
    subcategory: "Home Products",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.2,
    reviewCount: 18,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },

  // ECO PRODUCTS - Kitchen Products
  {
    id: "eco-kitchen-1",
    name: "Clay Pots & Pans Set",
    description: "Traditional clay cookware for healthy cooking.",
    price: 1200,
    discount: 0,
    category: "Eco Products",
    subcategory: "Kitchen Products",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviewCount: 47,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "eco-kitchen-2",
    name: "Cast Iron & Iron Cookware Set",
    description: "Durable cast iron cookware for traditional cooking methods.",
    price: 2500,
    discount: 10,
    category: "Eco Products",
    subcategory: "Kitchen Products",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviewCount: 52,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "eco-kitchen-3",
    name: "Traditional Stone Grinders (Aattukal, Ammi Kal)",
    description: "Authentic stone grinders for traditional food preparation.",
    price: 1800,
    discount: 0,
    category: "Eco Products",
    subcategory: "Kitchen Products",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 33,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },

  // ECO PRODUCTS - Eco-Friendly Stationery
  {
    id: "eco-stationery-1",
    name: "Seed Paper Notebooks - Set of 3",
    description: "Plantable notebooks with recycled paper embedded with seeds.",
    price: 350,
    discount: 0,
    category: "Eco Products",
    subcategory: "Eco-Friendly Stationery",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviewCount: 64,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "eco-stationery-2",
    name: "Plantable Pencils - Pack of 10",
    description: "Pencils with seed capsules that grow into plants when planted.",
    price: 280,
    discount: 0,
    category: "Eco Products",
    subcategory: "Eco-Friendly Stationery",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviewCount: 39,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },
  {
    id: "eco-stationery-3",
    name: "Recycled Paper Products - Assorted",
    description: "Collection of stationery items made from recycled paper.",
    price: 220,
    discount: 5,
    category: "Eco Products",
    subcategory: "Eco-Friendly Stationery",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.2,
    reviewCount: 27,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },

  // ECO PRODUCTS - Cleaning Essentials
  {
    id: "eco-cleaning-1",
    name: "Herbal Floor Cleaners - 1L",
    description: "Natural floor cleaner made from herbal ingredients.",
    price: 280,
    discount: 0,
    category: "Eco Products",
    subcategory: "Cleaning Essentials",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 43,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "eco-cleaning-2",
    name: "Natural Dishwash Powders (Soapnut, Shikakai) - 500g",
    description: "Traditional dish washing powder made from natural ingredients.",
    price: 180,
    discount: 0,
    category: "Eco Products",
    subcategory: "Cleaning Essentials",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.4,
    reviewCount: 31,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "eco-cleaning-3",
    name: "Cow Dung Cakes (Pooja + Cleaning Purpose) - Pack of 10",
    description: "Traditional dried cow dung cakes for ritual and cleaning purposes.",
    price: 150,
    discount: 0,
    category: "Eco Products",
    subcategory: "Cleaning Essentials",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.3,
    reviewCount: 25,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },

  // HERBAL PRODUCTS - Raw Herbs
  {
    id: "herbal-raw-1",
    name: "Thuthuvalai (Solanum Trilobatum) - 100g",
    description: "Medicinal herb used in traditional remedies for respiratory health.",
    price: 120,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Raw Herbs",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviewCount: 38,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "herbal-raw-2",
    name: "Adathodai (Malabar Nut) - 100g",
    description: "Traditional herb used for respiratory and bronchial conditions.",
    price: 110,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Raw Herbs",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviewCount: 29,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "herbal-raw-3",
    name: "Thulasi (Holy Basil) - 100g",
    description: "Sacred herb with medicinal properties for immunity and respiratory health.",
    price: 90,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Raw Herbs",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviewCount: 52,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "herbal-raw-4",
    name: "Karpooravalli (Mexican Mint) - 100g",
    description: "Aromatic herb used for cough, cold and digestive issues.",
    price: 100,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Raw Herbs",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 33,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },
  {
    id: "herbal-raw-5",
    name: "Vetiver Roots - 100g",
    description: "Aromatic roots used in traditional medicine and for cooling properties.",
    price: 180,
    discount: 5,
    category: "Herbal Products",
    subcategory: "Raw Herbs",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.4,
    reviewCount: 27,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "herbal-raw-6",
    name: "Arugampul (Bermuda Grass) - 100g",
    description: "Medicinal grass used in traditional remedies for various ailments.",
    price: 95,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Raw Herbs",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.3,
    reviewCount: 21,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },

  // HERBAL PRODUCTS - Herbal Powders
  {
    id: "herbal-powder-1",
    name: "Triphala Powder - 200g",
    description: "Traditional Ayurvedic blend of three fruits for digestion and detoxification.",
    price: 280,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Herbal Powders",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 57,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "herbal-powder-2",
    name: "Ashwagandha Powder - 200g",
    description: "Pure ashwagandha root powder for stress relief and immunity.",
    price: 320,
    discount: 10,
    category: "Herbal Products",
    subcategory: "Herbal Powders",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviewCount: 68,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "herbal-powder-3",
    name: "Nannari Powder - 200g",
    description: "Cooling herb powder used for making traditional summer drinks.",
    price: 250,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Herbal Powders",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviewCount: 41,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "herbal-powder-4",
    name: "Avarampoo Powder - 200g",
    description: "Traditional herb powder used for skin health and liver function.",
    price: 230,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Herbal Powders",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.4,
    reviewCount: 33,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },
  {
    id: "herbal-powder-5",
    name: "Brahmi Powder - 200g",
    description: "Ayurvedic herb powder known for cognitive enhancement and memory support.",
    price: 290,
    discount: 5,
    category: "Herbal Products",
    subcategory: "Herbal Powders",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviewCount: 49,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },

  // HERBAL PRODUCTS - Herbal Juices & Extracts
  {
    id: "herbal-juice-1",
    name: "Noni Juice - 500ml",
    description: "Pure noni fruit juice known for its numerous health benefits.",
    price: 450,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Herbal Juices & Extracts",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviewCount: 49,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "herbal-juice-2",
    name: "Amla Juice - 500ml",
    description: "Natural amla juice for immunity and vitamin C boost.",
    price: 320,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Herbal Juices & Extracts",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviewCount: 56,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "herbal-juice-3",
    name: "Aloe Vera Juice - 500ml",
    description: "Pure aloe vera juice for digestive health and skin care.",
    price: 350,
    discount: 5,
    category: "Herbal Products",
    subcategory: "Herbal Juices & Extracts",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 42,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "herbal-juice-4",
    name: "Thulasi Extract - 100ml",
    description: "Concentrated holy basil extract for respiratory health.",
    price: 280,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Herbal Juices & Extracts",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.4,
    reviewCount: 31,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },

  // HERBAL PRODUCTS - Health Mixes
  {
    id: "herbal-health-1",
    name: "Sathu Maavu (Millet Health Mix) - 500g",
    description: "Nutritious multi-grain health mix with millets and pulses.",
    price: 380,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Health Mixes",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviewCount: 63,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "herbal-health-2",
    name: "Sukku Malli Coffee Powder - 250g",
    description: "Traditional spiced coffee substitute with dry ginger and coriander.",
    price: 220,
    discount: 0,
    category: "Herbal Products",
    subcategory: "Health Mixes",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviewCount: 37,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "herbal-health-3",
    name: "Siddha Herbal Teas - Assorted Pack",
    description: "Collection of traditional herbal teas for various health benefits.",
    price: 350,
    discount: 5,
    category: "Herbal Products",
    subcategory: "Health Mixes",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 42,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },

  // NATURAL COSMETICS - Hair Care
  {
    id: "cosmetics-hair-1",
    name: "Herbal Hair Oil (Bhringraj, Amla, Hibiscus Oil) - 200ml",
    description: "Traditional hair oil blend for hair growth and nourishment.",
    price: 350,
    discount: 0,
    category: "Natural Cosmetics",
    subcategory: "Hair Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviewCount: 75,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "cosmetics-hair-2",
    name: "Shikakai Powder - 200g",
    description: "Natural hair cleanser and conditioner.",
    price: 180,
    discount: 5,
    category: "Natural Cosmetics",
    subcategory: "Hair Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 58,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "cosmetics-hair-3",
    name: "Reetha (Soapnut) - 200g",
    description: "Natural hair wash ingredient for gentle cleansing.",
    price: 160,
    discount: 0,
    category: "Natural Cosmetics",
    subcategory: "Hair Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.4,
    reviewCount: 39,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "cosmetics-hair-4",
    name: "Amla Powder - 200g",
    description: "Natural hair conditioner and strengthener.",
    price: 170,
    discount: 0,
    category: "Natural Cosmetics",
    subcategory: "Hair Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviewCount: 47,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "cosmetics-hair-5",
    name: "Vetiver Comb",
    description: "Aromatic wooden comb with cooling properties for scalp health.",
    price: 250,
    discount: 0,
    category: "Natural Cosmetics",
    subcategory: "Hair Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.3,
    reviewCount: 31,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },

  // NATURAL COSMETICS - Skin Care
  {
    id: "cosmetics-skin-1",
    name: "Turmeric Soap - 100g",
    description: "Handmade soap with turmeric for clear and glowing skin.",
    price: 120,
    discount: 0,
    category: "Natural Cosmetics",
    subcategory: "Skin Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviewCount: 62,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "cosmetics-skin-2",
    name: "Aloe Vera Gel - 150g",
    description: "Pure aloe vera gel for skin hydration and soothing.",
    price: 220,
    discount: 10,
    category: "Natural Cosmetics",
    subcategory: "Skin Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviewCount: 84,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "cosmetics-skin-3",
    name: "Multani Mitti Powder - 200g",
    description: "Natural clay for deep cleansing and skin purification.",
    price: 150,
    discount: 0,
    category: "Natural Cosmetics",
    subcategory: "Skin Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviewCount: 43,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "cosmetics-skin-4",
    name: "Neem Soap - 100g",
    description: "Handmade neem soap for skin purification and acne control.",
    price: 110,
    discount: 0,
    category: "Natural Cosmetics",
    subcategory: "Skin Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 53,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "cosmetics-skin-5",
    name: "Sandalwood Powder - 100g",
    description: "Pure sandalwood powder for skin brightening and cooling.",
    price: 280,
    discount: 0,
    category: "Natural Cosmetics",
    subcategory: "Skin Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviewCount: 57,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },

  // NATURAL COSMETICS - Bath & Body
  {
    id: "cosmetics-bath-1",
    name: "Herbal Bath Powders (Nalangu Maavu) - 200g",
    description: "Traditional bath powder with green gram, herbs, and flowers.",
    price: 280,
    discount: 0,
    category: "Natural Cosmetics",
    subcategory: "Bath & Body",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 48,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "cosmetics-bath-2",
    name: "Rose Water - 200ml",
    description: "Pure distilled rose water for skin toning and refreshing.",
    price: 180,
    discount: 0,
    category: "Natural Cosmetics",
    subcategory: "Bath & Body",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.7,
    reviewCount: 59,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "cosmetics-bath-3",
    name: "Essential Oils Set (Lavender, Tea Tree, Eucalyptus) - 30ml each",
    description: "Set of pure essential oils for aromatherapy and natural remedies.",
    price: 750,
    discount: 5,
    category: "Natural Cosmetics",
    subcategory: "Bath & Body",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.8,
    reviewCount: 67,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },

  // NATURAL COSMETICS - Oral Care
  {
    id: "cosmetics-oral-1",
    name: "Herbal Tooth Powder - 100g",
    description: "Natural tooth powder with herbs for dental hygiene.",
    price: 150,
    discount: 0,
    category: "Natural Cosmetics",
    subcategory: "Oral Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.5,
    reviewCount: 43,
    inStock: true,
    isNew: false,
    isFeatured: true,
  },
  {
    id: "cosmetics-oral-2",
    name: "Neem Sticks (Chew Sticks) - Pack of 10",
    description: "Traditional neem twigs for natural dental care.",
    price: 120,
    discount: 0,
    category: "Natural Cosmetics",
    subcategory: "Oral Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.3,
    reviewCount: 31,
    inStock: true,
    isNew: false,
    isFeatured: false,
  },
  {
    id: "cosmetics-oral-3",
    name: "Bamboo Toothbrush - Pack of 4",
    description: "Eco-friendly toothbrushes with bamboo handles.",
    price: 280,
    discount: 5,
    category: "Natural Cosmetics",
    subcategory: "Oral Care",
    image: "/placeholder.svg?height=400&width=400",
    rating: 4.6,
    reviewCount: 52,
    inStock: true,
    isNew: true,
    isFeatured: false,
  },
]

// Function to get all products
export async function getProducts(): Promise<Product[]> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 500))
  return mockProducts
}

// Function to get a single product by ID
export async function getProductById(id: string): Promise<Product | undefined> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 300))
  return mockProducts.find((product) => product.id === id)
}

// Function to get featured products
export async function getFeaturedProducts(): Promise<Product[]> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 300))
  return mockProducts.filter((product) => product.isFeatured)
}

// Function to get products by category
export async function getProductsByCategory(category: string): Promise<Product[]> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 300))
  return mockProducts.filter((product) => product.category.toLowerCase() === category.toLowerCase())
}
